acme_demo_article_list:
    path: /article/list
    defaults: {_controller: AcmeDemoBundle:Article:list}

acme_demo_article_show:
    path: /article/show/{id}
    defaults: {_controller: AcmeDemoBundle:Article:show}

acme_demo_article_add:
    path: /article/add
    defaults: {_controller: AcmeDemoBundle:Article:add}
